# Generated by Django 5.2.13 on 2026-06-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_status',
            field=models.CharField(choices=[('none', 'No media'), ('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='avatars/thumbnails/'),
        ),
    ]
