# Generated by Django 5.2.13 on 2026-04-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
