# Generated by Django 5.2.13 on 2026-04-30 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_alter_tweet_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['tweet', '-created_at'], name='tweets_comm_tweet_i_ad6d78_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['-created_at'], name='tweets_twee_created_d01740_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['user', '-created_at'], name='tweets_twee_user_id_f44754_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['slug'], name='tweets_twee_slug_943afb_idx'),
        ),
    ]
