# Generated by Django 5.2.13 on 2026-06-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_alter_tweet_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='media_status',
            field=models.CharField(choices=[('none', 'No media'), ('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='none', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='tweet',
            name='media_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='tweet_media/thumbnails/'),
        ),
    ]
